export const ROUTES = Object.freeze({
  HOME: 'HOME',
  LOCALIZE: 'LOCALIZE',
  WEBVIEW: 'WEBVIEW',
  CHECKBOX: 'CHECKBOX',
  VIDEO: 'VIDEO',
  VIDEO_PLAYER: 'VIDEO_PLAYER',
  FLYOUT: 'FLYOUT',
  VIDEO_AUDIO: 'VIDEO_AUDIO',
  ASYNC_STORAGE: 'ASYNC_STORAGE',
  SENSITIVE_INFO: 'SENSITIVE_INFO',
});
