export const ROUTES = Object.freeze({
  HOME: 'HOME',
  LOCALIZE: 'LOCALIZE',
  WEBVIEW: 'WEBVIEW',
  CHECKBOX: 'CHECKBOX',
  VIDEO: 'VIDEO',
  VIDEO_PLAYER: 'VIDEO_PLAYER',
  FLYOUT: 'FLYOUT',
  VIDEO_AUDIO: 'VIDEO_AUDIO',
  ASYNC_STORAGE: 'ASYNC_STORAGE',
  SENSITIVE_INFO: 'SENSITIVE_INFO',
  PERMISSIONS: 'PERMISSIONS',
  CAMERA: 'CAMERA',
  LINEAR_GRADIENT: 'LINEAR_GRADIENT',
  DEVICE_INFO: 'DEVICE_INFO',
  BLOB_UTIL: 'BLOB_UTIL',
  SLIDER: 'SLIDER',
  PROGRESS_VIEW: 'PROGRESS_VIEW',
  NETINFO: 'NETINFO',
  DATETIMEPICKER: 'DATETIMEPICKER',
  CLIPBOARD: 'CLIPBOARD',
  EXPANDER: 'EXPANDER',
  CONFIG: 'CONFIG',
  // DO NOT WORK
  TRACK_PLAYER_AUDIO: 'TRACK_PLAYER_AUDIO',
  PRINT: 'PRINT',
  // XAML: 'XAML',
  // PDF: 'PDF',
  // DOCUMENT_PICKER: 'DOCUMENT_PICKER', // CSharp
  // SQLITE_STORAGE: 'SQLITE_STORAGE', // CPP, but package is old
  // FILE_VIEWER: 'FILE_VIEWER',
  // TEXT_TO_SPEECH: 'TEXT_TO_SPEECH', // CPP, but package is old
  // FS: 'FS', // CPP impl is not merged
  // GESTURE_HANDLER: 'GESTURE_HANDLER', // CPP impl is not merged
});
